apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-dags-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-gcs-test-sc-1
